# Use a imagem oficial do Node.js como a base
FROM node:latest

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos de package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie todos os arquivos para o diretório de trabalho
COPY . .

# Exponha a porta 3000 (ou a porta em que seu aplicativo React está rodando)
EXPOSE 3000

# Comando para iniciar o aplicativo React
CMD ["npm", "start", "--port", "3000"]